easy_admin:
    site_name: 'API Panel'
    design:
#        assets:
#            css: ['assets/custom.css']
#        brand_color: '#7CB900'
        menu:
        - label: 'Veri Yönetimi'
          roles: ['ROLE_SUPER_ADMIN']
          children: ['Users']
    entities:
        Users:
            class: App\Admin\Entity\User
            permissions:
                list: ['ROLE_SUPER_ADMIN']
                new: ['ROLE_SUPER_ADMIN']
                edit: ['ROLE_SUPER_ADMIN']
                delete: ['ROLE_SUPER_ADMIN']
                show: ['ROLE_SUPER_ADMIN']
