easy_admin:
    site_name: 'API Panel'
    design:
        templates:
            menu: 'src/Admin/Resources/views/menu.html.twig'
        menu:
        - label: 'Veri Yönetimi'
          roles: ['ROLE_SUPER_ADMIN']
          children: ['Users']
        - { entity: Tickets, label: Tickets , icon: support}
    entities:
        Users:
            class: App\Admin\Entity\User
            permissions:
                list: ['ROLE_SUPER_ADMIN']
                new: ['ROLE_SUPER_ADMIN']
                edit: ['ROLE_SUPER_ADMIN']
                delete: ['ROLE_SUPER_ADMIN']
                show: ['ROLE_SUPER_ADMIN']
        Tickets:
            class: App\Admin\Entity\Ticket
            controller: App\Admin\Controller\TicketController
            permissions:
                list: ['ROLE_ADMIN']
                new: ['ROLE_ADMIN']
                edit: ['ROLE_ADMIN']
                delete: ['ROLE_ADMIN']
                show: ['ROLE_ADMIN']
            list:
               fields:
                   - { property: id }
                   - { property: subject, label: Konu }
                   - { property: createdBy, label: Oluşturan }
                   - { property: departmentDesc, label: Departman }
                   - { property: statusDesc, label: Durum }
            form:
                fields:
                    - {property: subject, type: text, label: 'Konu', type_options: { disabled: true }}
                    - property: 'department'
                      label: 'Departman'
                      type: 'choice'
                      type_options:
                          choices: !php/const App\Admin\Entity\Ticket::DEPARTMENT_LIST
                          disabled: true
#                    - property: 'messages'
#                      type: 'collection'
#                      type_options:
#                          entry_type: 'App\Admin\Form\TicketMessageFormType'
#                          allow_delete: true
#                          allow_add: true
#                          by_reference: false

