# config/packages/fos_user.yaml
fos_user:
  service:
    mailer: fos_user.mailer.twig_swift
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Admin\Entity\User
  from_email:
    address: manage@hosted.com.tr
    sender_name: HOSTED Technology
  registration:
    form:
      type: App\Admin\Form\RegistrationFormType
    confirmation:
      enabled:    true
      template:   'bundles/FOSUserBundle/Registration/email.txt.twig'
